
mariadb:
  image: mariadb:latest
  environment:
    MYSQL_MANAGED : false
    MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    MYSQL_MAX_CONNECTIONS: ${MYSQL_MAX_CONNECTIONS}
    MYSQL_BUFFER_POOL: ${MYSQL_BUFFER_POOL}
    MYSQL_SSL_ENABLE: ${MYSQL_SSL_ENABLE}
    MYSQL_SSL_CA: ${MYSQL_SSL_CA}
    MYSQL_SSL_KEY: ${MYSQL_SSL_KEY}
    MYSQL_SSL_CRT: ${MYSQL_SSL_CRT}
    MYSQL_REPLICATION_MODE : ${MYSQL_REPLICATION_MODE}
    MYSQL_REPLICATION_USER  : ${MYSQL_REPLICATION_USER}
    MYSQL_REPLICATION_PASSWORD : ${MYSQL_REPLICATION_PASSWORD}
    MYSQL_MASTER_HOST : ${MYSQL_MASTER_HOST}
    MYSQL_MASTER_PORT : ${MYSQL_MASTER_PORT}
    MYSQL_RESET_SLAVE : ${MYSQL_RESET_SLAVE}
  volumes:
    -  ${MYSQL_VOLUME}:/apps/mariadb
  tty: true
  stdin_open: true
  mem_limit: ${MEM_LIMIT}
  volume_driver: ${VOLUME_DRIVER}
  restart: ${RESTART_POLICIES}
